### ISSUE TITLE
ResourceManager and dispose

### ISSUE THREAD

**Issue by joelseverin** [Jokab/Bullet-Inferno#7]
- The resource manager needs to use the AssetManager.unload.
- We have to replace texture.dispose() with resourceManager.unload everywhere.

Maybe we can wrap the textures and and have a:
## ManagedTexture
- getTexture()
- dispose()
  ?

**Comment by verath** [comment]
We have decided to not dispose of separate textures and instead disposing the resource manager (which in turn disposes the asset manager). 

This is because It seems like the asset manager is made for having textures always loaded, and only reload them on resume and start of the game. Unloading should only be done if the texture will never be used again in the application life.
